x-veld:
  executable:

    inputs:
      volume: /veld/input/
      type: "conllu"
      content: 
        - "tokenized text"
        - "enriched text"
        - "linguistic data"

    outputs:
      volume: /veld/output/
      type: "udpipe model"
      content:
        - "NLP model"
        - "tokenizer"
        - "lemmatizer"

    environment:
      train_data_path:
        path_prefix: "/veld/input/"
        type: "conllu"
      model_path:
        path_prefix: "/veld/output/"
        type: "udpipe model"

services:
  veld:
    build: .
    volumes:
      - ./volumes/train/input/:/veld/input/
      - ./volumes/train/output/:/veld/output/
      - ./src/:/veld/executable/
    environment:
      train_data_path: "/veld/input/<REPLACE>"
      model_path: "/veld/output/<REPLACE>"
    command: /veld/executable/train.sh

