x-veld:
  executable:

    inputs:
      - volume: /veld/input/1/
        input: "txt"
        content: "natural text"
      - volume: /veld/input/2/
        type: "udpipe model"
        content:
          - "NLP model"
          - "tokenizer"
          - "lemmatizer"

    outputs:
      volume: /veld/output/
      type: "conllu"
      content: 
        - "tokenized text"
        - "enriched text"
        - "linguistic data"

    environment:
      input_text_file_path:
        path_prefix: "/veld/input/1/"
        type: "txt"
      model_file_Path: 
        path_prefix: "/veld/input/2/"
        type: "udpipe model"
      output_conllu_file_path:
        path_prefix: "/veld/output/"
        type: "conllu"

services:
  veld:
    build: .
    volumes:
      - ./volumes/tokenize/input/1/:/veld/input/1/ 
      - ./volumes/tokenize/input/2/:/veld/input/2/
      - ./volumes/tokenize/output/:/veld/output/
      - ./src/main/:/veld/executable/
    environment:
      input_text_file_path: "/veld/input/1/<REPLACE>"
      model_path: "/veld/input/2/<REPLACE>"
      output_conllu_file_path: "/veld/output/<REPLACE>"
    command: /veld/executable/tokenize.sh


